/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import AppPackage.AnimationClass;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpingreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlbinternet = new javax.swing.JLabel();
        jlbcalculadora = new javax.swing.JLabel();
        jlbmusica = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpmenu = new javax.swing.JLabel();
        jpmenu1 = new javax.swing.JLabel();
        jpmenu2 = new javax.swing.JLabel();
        jpmenu3 = new javax.swing.JLabel();
        jpmenu4 = new javax.swing.JLabel();
        jpmenu5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpingreso.setBackground(new java.awt.Color(255, 255, 255));
        jpingreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_User_96px_2.png"))); // NOI18N
        jpingreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 120));

        jLabel2.setBackground(new java.awt.Color(238, 112, 82));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 112, 82));
        jLabel2.setText("USUARIO:");
        jpingreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, 20));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("CONTRASEÑA:");
        jpingreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 20));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("INGRESE USUARIO");
        jTextField1.setBorder(null);
        jpingreso.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 170, 30));
        jpingreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 230, 30));
        jpingreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 220, 10));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setBorder(null);
        jpingreso.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 180, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_customer_32px_1.png"))); // NOI18N
        jpingreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Key_32px.png"))); // NOI18N
        jpingreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Menu_32px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jpingreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Enter_ON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Enter_ON.png"))); // NOI18N
        jpingreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 385, 100, 40));

        jlbinternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Globe_32px.png"))); // NOI18N
        jpingreso.add(jlbinternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 50, -1, 30));

        jlbcalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Calculator_32px.png"))); // NOI18N
        jpingreso.add(jlbcalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 90, -1, 30));

        jlbmusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Musical_Notes_32px.png"))); // NOI18N
        jpingreso.add(jlbmusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 130, -1, 30));

        getContentPane().add(jpingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Maintenance_96px.png"))); // NOI18N
        jpmenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenuMouseMoved(evt);
            }
        });
        jpmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenuMouseExited(evt);
            }
        });
        jPanel1.add(jpmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 140, 130));

        jpmenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Today_96px.png"))); // NOI18N
        jpmenu1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu1MouseMoved(evt);
            }
        });
        jpmenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu1MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 120));

        jpmenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Clock_96px.png"))); // NOI18N
        jpmenu2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu2MouseMoved(evt);
            }
        });
        jpmenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu2MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 140, 120));

        jpmenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Idea_96px.png"))); // NOI18N
        jpmenu3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu3MouseMoved(evt);
            }
        });
        jpmenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu3MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, 130));

        jpmenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Handshake_96px.png"))); // NOI18N
        jpmenu4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu4MouseMoved(evt);
            }
        });
        jpmenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu4MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 140, 120));

        jpmenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Google_Drive_96px.png"))); // NOI18N
        jpmenu5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpmenu5MouseMoved(evt);
            }
        });
        jpmenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpmenu5MouseExited(evt);
            }
        });
        jPanel1.add(jpmenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, 120));

        jLabel7.setBackground(new java.awt.Color(255, 99, 71));
        jLabel7.setForeground(new java.awt.Color(255, 99, 71));
        jLabel7.setText("socios");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 50, -1));

        jLabel8.setBackground(new java.awt.Color(255, 99, 71));
        jLabel8.setForeground(new java.awt.Color(255, 99, 71));
        jLabel8.setText("programarador");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 99, 71));
        jLabel9.setForeground(new java.awt.Color(255, 99, 71));
        jLabel9.setText("cronograma");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 99, 71));
        jLabel10.setForeground(new java.awt.Color(255, 99, 71));
        jLabel10.setText("mantenimiento ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 20));

        jLabel11.setBackground(new java.awt.Color(255, 99, 71));
        jLabel11.setForeground(new java.awt.Color(255, 99, 71));
        jLabel11.setText("notas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 30, -1));

        jLabel12.setBackground(new java.awt.Color(255, 99, 71));
        jLabel12.setForeground(new java.awt.Color(255, 99, 71));
        jLabel12.setText("drivers");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("buscar");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 91)));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 200, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Search_32px_2.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Multiply_32px.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        AnimationClass internet=new AnimationClass();
        internet.jLabelXRight(-40, 10, 10, 5, jlbinternet);
        
        AnimationClass calculadora=new AnimationClass();
        calculadora.jLabelXRight(-40, 10, 10, 5, jlbcalculadora);
        
        AnimationClass musica=new AnimationClass();
        musica.jLabelXRight(-40, 10, 10, 5, jlbmusica);
        
        //<----
        AnimationClass internett=new AnimationClass();
        internett.jLabelXLeft(10, -40, 10, 5, jlbinternet);
        
         AnimationClass calculadoraa=new AnimationClass();
        calculadoraa.jLabelXLeft(10, -40, 10, 5, jlbcalculadora);
        
        AnimationClass musicaa=new AnimationClass();
        musicaa.jLabelXLeft(10, -40, 10, 5, jlbmusica);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setState(Login.ICONIFIED);
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        int dialog= JOptionPane.YES_NO_OPTION;
        int result=JOptionPane.showConfirmDialog(null, "Desea salir del Login","Exit",dialog);
        if(result==0)
        {
            System.exit(0);
            
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jpmenu1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu1MouseMoved
        jpmenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
        
    }//GEN-LAST:event_jpmenu1MouseMoved

    private void jpmenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu1MouseExited
        jpmenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpmenu1MouseExited

    private void jpmenu2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu2MouseMoved
        jpmenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpmenu2MouseMoved

    private void jpmenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu2MouseExited
        jpmenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpmenu2MouseExited

    private void jpmenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenuMouseMoved
        jpmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpmenuMouseMoved

    private void jpmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenuMouseExited
        jpmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpmenuMouseExited

    private void jpmenu3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu3MouseMoved
        jpmenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpmenu3MouseMoved

    private void jpmenu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu3MouseExited
        jpmenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpmenu3MouseExited

    private void jpmenu5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu5MouseMoved
        jpmenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpmenu5MouseMoved

    private void jpmenu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu5MouseExited
        jpmenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpmenu5MouseExited

    private void jpmenu4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu4MouseMoved
        jpmenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpmenu4MouseMoved

    private void jpmenu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpmenu4MouseExited
        jpmenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpmenu4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlbcalculadora;
    private javax.swing.JLabel jlbinternet;
    private javax.swing.JLabel jlbmusica;
    private javax.swing.JPanel jpingreso;
    private javax.swing.JLabel jpmenu;
    private javax.swing.JLabel jpmenu1;
    private javax.swing.JLabel jpmenu2;
    private javax.swing.JLabel jpmenu3;
    private javax.swing.JLabel jpmenu4;
    private javax.swing.JLabel jpmenu5;
    // End of variables declaration//GEN-END:variables
}
